name: Upload to PyPi

on:
  release:
    types:
      - published

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: pypa/gh-action-pypi-publish@release/v1
    - name: "Publish to Pypi::  ${{ github.ref }}"
      with:
        username: __token__
        password: ${{ secrets.PYPI_API_TOKEN }}
        verbose: true
