name: Upload to PyPi

on:
  release:
    types:
      - published

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Set up Python 3.9
      uses: actions/setup-python@v1
      with:
        python-version: '3.x'
    - name: Install pypa/build
      run: >-
        python -m
        pip install
        build
        --user
    - name: Test
      run: |
        rm -rf build dist *.egg-info
        python resetup.py --version="${{ github.ref }}"
    - name: Build a binary wheel and a source tarball
      run: >-
        python -m
        build
        --sdist
        --wheel
        --outdir dist/
        .
    - name: "Publish to Pypi::  ${{ github.ref }}"
      uses: pypa/gh-action-pypi-publish@master
      with:
        username: __token__
        password: ${{ secrets.PYPI_API_TOKEN }}
        verbose: true
